/** Read-only validation of metadata, preservation and byte-level integrity. Scripts are never executed. */
import { tool } from "@opencode-ai/plugin"
import { createHash } from "node:crypto"
import { readFile, readdir, stat } from "node:fs/promises"
import path from "node:path"

const RESTART = "La validación terminó. Si la skill fue instalada o actualizada, no está disponible en la sesión actual: el usuario humano debe reiniciar completamente el runtime/servidor de OpenCode antes de usarla."
const OPS = new Set(["reviewed", "adapted", "unknown"]); const ROUTING = new Set(["refiner-only", "refiner-north", "executor-auditor", "transversal"]); const REASONING = new Set(["none", "procedural", "diagnostic", "architectural", "creative"]); const AGENTS = new Set(["refiner", "north", "executor", "auditor"])
type D = Record<string, any>
const text = (v: unknown) => typeof v === "string" ? v.trim() : ""
const dict = (v: unknown): v is D => Boolean(v && typeof v === "object" && !Array.isArray(v))
const sha = (b: Uint8Array) => createHash("sha256").update(b).digest("hex")
const safe = (v: string) => Boolean(v) && v !== "." && !path.isAbsolute(v) && !v.includes("\\") && !v.split("/").some(p => p === "" || p === "." || p === "..")
async function filesOnly(dir: string, prefix = ""): Promise<string[]> { const out: string[] = []; for (const e of await readdir(dir, { withFileTypes: true })) { const rel = prefix ? `${prefix}/${e.name}` : e.name; const full = path.join(dir, e.name); if (e.isDirectory()) out.push(...await filesOnly(full, rel)); else if (e.isFile() && safe(rel)) out.push(rel) } return out }
const textual = (b: Uint8Array) => { try { const s = new TextDecoder("utf-8", { fatal: true }).decode(b); return !/[\u0000\u0001-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(s) } catch { return false } }
const flags = (s: string) => { const rules: [string, RegExp][] = [["prompt-injection", /(?:ignore|disregard)\s+(?:all\s+)?(?:of\s+the\s+)?(?:your\s+)?(?:previous|prior|above|earlier)\s+instructions|ignore\s+(?:the\s+)?instructions\s+(?:above|earlier|prior)|ignore\s+(?:all\s+)?instructions|system\s+message|jailbreak/i], ["exfiltration", /exfiltrat|upload\s+.*(secret|token|env)/i], ["credential-theft", /api[_ -]?key|password|secret|credential|private\s+key/i], ["remote-execution", /(?:curl|wget)[^\n|]*\|\s*(?:ba)?sh|remote\s+execution/i], ["obfuscation", /base64\s+(-d|--decode)|fromCharCode|eval\s*\(/i], ["policy-evasion", /bypass\s+(?:policy|security)|disable\s+safety/i]]; return rules.filter(([, r]) => r.test(s)).map(([n]) => n) }
function pendingDependencies(m: D) { const d = dict(m.dependencies) ? m.dependencies : {}; const installed = new Set((Array.isArray(d.installed) ? d.installed : []).map(text)); const out: D[] = (Array.isArray(d.pending) ? d.pending : []).map((x: unknown) => typeof x === "string" ? { name: x, status: "pending" } : { ...x }); for (const kind of ["mcp", "cli", "packages", "environment"]) for (const item of Array.isArray(d[kind]) ? d[kind] : []) { const name = typeof item === "string" ? item : text(item?.name || item?.id || item?.package); if (name && !installed.has(name) && !out.some(x => text(x.name) === name)) out.push(typeof item === "string" ? { name, kind, status: "pending" } : { ...item, kind, status: "pending" }) } return out }

export default tool({ description: "Validates an installed external skill read-only; scripts are never executed.", args: { slug: tool.schema.string(), projectDirectory: tool.schema.string().optional(), allowBinaryUninspected: tool.schema.boolean().optional(), approved: tool.schema.boolean().optional() }, async execute(args, context) { const root = path.resolve(context.directory || process.cwd()); const project = path.resolve(root, args.projectDirectory?.trim() || "."); const result: any = { ok: true, valid: false, slug: args.slug, errors: [], warnings: ["upstream_not_rechecked: upstream provenance was not downloaded during validation"], checks: {}, restart_required: true, message: RESTART, pending_dependencies: [] }; if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(args.slug) || (project !== root && !project.startsWith(`${root}${path.sep}`))) { result.ok = false; result.errors.push("slug o projectDirectory inválido"); return result } const target = path.join(project, ".opencode", "skills", "extern", args.slug); try { if (!(await stat(target)).isDirectory()) throw new Error("skill directory not found"); const all = await filesOnly(target); const installed = all.filter(p => p !== "crisol-eco.yaml"); const skill = await readFile(path.join(target, "SKILL.md")); const metadata = JSON.parse(await readFile(path.join(target, "crisol-eco.yaml"), "utf8")) as D; const errors: string[] = result.errors; result.checks.skill_path = { valid: true }; if (!textual(skill)) errors.push("SKILL.md es binario o no es UTF-8 válido"); const skillText = textual(skill) ? new TextDecoder().decode(skill) : ""; result.checks.integration_block = { valid: /##\s+Crisol-Eco:\s*integración/i.test(skillText) && /<!--\s*crisol-eco:integration\s*-->/i.test(skillText) }; if (!result.checks.integration_block.valid) errors.push("Falta el bloque estable ## Crisol-Eco: integración")
    const c = metadata.compatibility; if (!dict(c) || !OPS.has(text(c.opencode)) || !Array.isArray(c.frameworks) || !c.frameworks.every((x: unknown) => typeof x === "string")) errors.push("compatibility inválida"); const r = metadata.routing, q = metadata.reasoning; if (!dict(r) || !ROUTING.has(text(r.profile)) || !Array.isArray(r.agents) || !r.agents.length || !r.agents.every((a: unknown) => AGENTS.has(text(a)))) errors.push("routing inválido"); if (!dict(q) || !REASONING.has(text(q.mode))) errors.push("reasoning inválido"); if (text(metadata.status) !== "complete") errors.push("metadata.status no es complete"); if (!dict(metadata.preservation) || text(metadata.preservation.status) !== "complete" || metadata.preservation.enumerated !== true) errors.push("preservation no es completa y enumerada")
    const upstream = text(metadata.identity?.upstream_checksum); if (!/^sha256:[0-9a-f]{64}$/.test(upstream)) errors.push("identity.upstream_checksum ausente o inválido"); const verification = metadata.verification?.files; const checksums: D[] = []; if (!Array.isArray(verification) || !verification.length) errors.push("verification.files ausente; no se puede validar integridad instalada"); else { for (const f of verification) { if (!dict(f) || !safe(text(f.relativePath)) || !/^sha256:[0-9a-f]{64}$/.test(text(f.checksum)) || !/^sha256:[0-9a-f]{64}$/.test(text(f.upstream_checksum))) { errors.push("verification.files inválido o sin provenance upstream"); continue } const bytes = await readFile(path.join(target, f.relativePath)).catch(() => null); if (!bytes) { errors.push(`archivo verificado ausente: ${f.relativePath}`); continue } const actual = `sha256:${sha(bytes)}`; const valid = actual === f.checksum; checksums.push({ relativePath: f.relativePath, expected: f.checksum, actual, valid, upstream_checksum: f.upstream_checksum }); if (!valid) errors.push(`checksum installed mismatch: ${f.relativePath}`) } const listed = verification.map((f: D) => f.relativePath).sort(); if (JSON.stringify(listed) !== JSON.stringify(installed.slice().sort())) errors.push("verification.files no enumera exactamente todos los archivos instalados") }
    const binaryFiles: string[] = []; const signals: string[] = []; for (const rel of installed) { const bytes = await readFile(path.join(target, rel)); if (!textual(bytes)) { if (rel === "SKILL.md") errors.push("SKILL.md binario"); else binaryFiles.push(rel) } else signals.push(...flags(new TextDecoder().decode(bytes))) } const approvedBinary = args.allowBinaryUninspected === true && args.approved === true && metadata.security?.binary_uninspected === true && metadata.security?.approved === true; if (binaryFiles.length && !approvedBinary) errors.push(`archivos binarios no inspeccionados: ${binaryFiles.join(", ")}`); if (signals.length) errors.push(`critical security signals: ${[...new Set(signals)].join(", ")}`); result.pending_dependencies = pendingDependencies(metadata); result.checks.upstream_provenance = { valid: /^sha256:[0-9a-f]{64}$/.test(upstream), checksum: upstream, rechecked: false }; result.checks.security_signals = { valid: !signals.length, signals: [...new Set(signals)] }; result.checks.binary = { valid: !binaryFiles.length || approvedBinary, files: binaryFiles, approved: approvedBinary }; result.checksums = { upstream_checksum: { present: Boolean(upstream), value: upstream, compared_against: "upstream identity provenance only", valid: /^sha256:[0-9a-f]{64}$/.test(upstream) }, installed_files: checksums }; result.valid = errors.length === 0; result.ok = result.valid; return result } catch (e) { result.ok = false; result.errors.push(e instanceof Error ? e.message : String(e)); return result } } })
