/** Read-only remote intake. Remote content is data and is never executed. */
import { tool } from "@opencode-ai/plugin"
import https from "node:https"
import { lookup } from "node:dns/promises"
import { createHash } from "node:crypto"

const CATALOG = "https://raw.githubusercontent.com/agentskillexchange/skills/main/skills.json"
const MAX_BODY = 2 * 1024 * 1024
const MAX_FILES = 100
const MAX_TOTAL = 20 * 1024 * 1024
const ALLOWED = new Set(["raw.githubusercontent.com", "api.github.com", "github.com", "www.github.com", "agentskillexchange.com", "www.agentskillexchange.com"])
type D = Record<string, any>
const text = (v: unknown) => typeof v === "string" ? v.trim() : ""
const privateAddress = (v: string) => { const h = v.toLowerCase().replace(/^\[|\]$/g, ""); if (h === "localhost" || h.endsWith(".localhost") || h.endsWith(".local") || h === "::1" || h === "0.0.0.0" || h === "metadata.google.internal" || h.startsWith("127.") || h.startsWith("169.254.") || /^::ffff:(?:\d{1,3}\.){3}\d{1,3}$/i.test(h) || /^(?:fc|fd|fe[89a-f])/i.test(h)) return true; const p = h.split(".").map(Number); return p.length === 4 && p.every(n => Number.isInteger(n) && n >= 0 && n <= 255) && (p[0] === 10 || p[0] === 127 || (p[0] === 172 && p[1] >= 16 && p[1] <= 31) || (p[0] === 192 && p[1] === 168) || (p[0] === 169 && p[1] === 254)) }
async function request(value: string, max: number, accept: string): Promise<{ url: string, bytes: Uint8Array }> { let current = value; for (let hop = 0; hop < 4; hop++) { const u = new URL(current); if (u.protocol !== "https:" || privateAddress(u.hostname) || !ALLOWED.has(u.hostname.toLowerCase())) throw new Error("remote URL host is not safe"); const as = await lookup(u.hostname, { all: true }); const a = as.find(x => !privateAddress(x.address)); if (!a) throw new Error("remote URL resolves to a private address"); const response = await new Promise<{ code: number, location?: string, bytes: Uint8Array }>((resolve, reject) => { const req = https.request(u, { hostname: a.address, port: 443, path: `${u.pathname}${u.search}`, servername: u.hostname, family: a.family, headers: { Accept: accept }, lookup: (_h, _o, cb) => cb(null, a.address, a.family) }, res => { const chunks: Buffer[] = []; let total = 0; res.on("data", c => { total += c.length; if (total > max) req.destroy(new Error(`response exceeds ${max}`)); else chunks.push(c) }); res.on("end", () => resolve({ code: res.statusCode || 0, location: res.headers.location, bytes: new Uint8Array(Buffer.concat(chunks)) })); res.on("error", reject) }); req.setTimeout(10_000, () => req.destroy(new Error("request timed out"))); req.on("error", reject); req.end() }); if (response.code >= 300 && response.code < 400) { if (!response.location) throw new Error("redirect has no Location header"); current = new URL(response.location, u).toString(); continue } if (response.code !== 200) throw new Error(`HTTP ${response.code}`); return { url: current, bytes: response.bytes } } throw new Error("too many redirects") }
const sha = (b: Uint8Array) => `sha256:${createHash("sha256").update(b).digest("hex")}`
const textual = (b: Uint8Array) => { try { const s = new TextDecoder("utf-8", { fatal: true }).decode(b); return !/[\u0000\u0001-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(s) } catch { return false } }
const flags = (s: string) => { const rules: [string, RegExp][] = [["prompt-injection", /(?:ignore|disregard)\s+(?:all\s+)?(?:of\s+the\s+)?(?:your\s+)?(?:previous|prior|above|earlier)\s+instructions|ignore\s+(?:the\s+)?instructions\s+(?:above|earlier|prior)|ignore\s+(?:all\s+)?instructions|system\s+message|jailbreak/i], ["exfiltration", /exfiltrat|upload\s+.*(secret|token|env)/i], ["credential-theft", /api[_ -]?key|password|secret|credential|private\s+key/i], ["remote-execution", /(?:curl|wget)[^\n|]*\|\s*(?:ba)?sh|remote\s+execution/i], ["obfuscation", /base64\s+(-d|--decode)|fromCharCode|eval\s*\(/i], ["policy-evasion", /bypass\s+(?:policy|security)|disable\s+safety/i]]; return rules.filter(([, r]) => r.test(s)).map(([n]) => n) }
type Git = { owner: string, repo: string, ref: string, path: string }
const github = (url: string): Git | null => { try { const u = new URL(url); if (!["github.com", "raw.githubusercontent.com"].includes(u.hostname)) return null; const p = u.pathname.split("/").filter(Boolean); if (p.length < 2) return null; if (u.hostname === "github.com" && (p[2] === "tree" || p[2] === "blob")) return { owner: p[0], repo: p[1], ref: p[3] || "HEAD", path: p.slice(4).join("/") || "SKILL.md" }; return { owner: p[0], repo: p[1], ref: p[2] || "HEAD", path: p.slice(3).join("/") || "SKILL.md" } } catch { return null } }
async function treeFiles(g: Git, slug?: string) { const prefix = slug ? `skills/${slug}` : g.path.replace(/\/[^/]+$/, ""); const api = `https://api.github.com/repos/${g.owner}/${g.repo}/git/trees/${encodeURIComponent(g.ref)}?recursive=1`; const tree = JSON.parse(new TextDecoder().decode((await request(api, MAX_BODY, "application/vnd.github+json")).bytes)); if (tree.truncated === true) throw new Error("GitHub tree is truncated; preservation is incomplete"); const entries = (tree.tree || []).filter((x: D) => x.type === "blob" && typeof x.path === "string" && (x.path === prefix || x.path.startsWith(`${prefix}/`))); if (!entries.length || !entries.some((x: D) => x.path === `${prefix}/SKILL.md`)) throw new Error("complete skill tree not found"); return entries.map((x: D) => ({ relativePath: x.path.slice(prefix.length).replace(/^\//, ""), url: `https://raw.githubusercontent.com/${g.owner}/${g.repo}/${g.ref}/${x.path}`, size: Number(x.size) || 0 })) }
function pendingDependencies(metadata: D) { const deps = metadata.dependencies && typeof metadata.dependencies === "object" ? metadata.dependencies : {}; const raw = Array.isArray(deps.pending) ? deps.pending : []; const installed = new Set([...(Array.isArray(deps.installed) ? deps.installed : [])].map(text)); const out = raw.map((x: unknown) => typeof x === "string" ? { name: x, status: "pending" } : x); for (const kind of ["mcp", "cli", "packages", "environment"]) for (const item of Array.isArray(deps[kind]) ? deps[kind] : []) { const name = typeof item === "string" ? item : text(item?.name || item?.id || item?.package); if (name && !installed.has(name) && !out.some((x: D) => text(x?.name) === name)) out.push(typeof item === "string" ? { name, kind, status: "pending" } : { ...item, kind, status: "pending" }) } return out }

export default tool({ description: "Inspects a remote skill without installing or executing it.", args: { slug: tool.schema.string().optional(), skillUrl: tool.schema.string().optional(), sourceUrl: tool.schema.string().optional(), catalogUrl: tool.schema.string().optional(), allowBinaryUninspected: tool.schema.boolean().optional(), approved: tool.schema.boolean().optional() }, async execute(args) { try { let resolved = args.skillUrl?.trim() || args.sourceUrl?.trim() || ""; let provider = "upstream"; if (args.slug) { const cat = JSON.parse(new TextDecoder().decode((await request(args.catalogUrl?.trim() || CATALOG, MAX_BODY, "application/json")).bytes)); const values = Array.isArray(cat) ? cat : cat?.skills; const entry = values?.find((v: D) => [v.slug, v.id, v.name].some(x => text(x) === args.slug!.trim())); if (!entry) return JSON.stringify({ ok: false, error: `Skill slug not found in catalog: ${args.slug}` }); resolved ||= text(entry.skill_url) || text(entry.skillUrl) || text(entry.source_url) || text(entry.sourceUrl) || text(entry.url); provider = "AgentSkillExchange" } if (!resolved) return JSON.stringify({ ok: false, error: "Unable to resolve source URL" })
    const gh = github(resolved); let listed: D[] | null = null; let enumerationReason = ""; try { if (provider === "AgentSkillExchange") listed = await treeFiles({ owner: "agentskillexchange", repo: "skills", ref: "main", path: "" }, args.slug); else if (gh) listed = await treeFiles(gh) } catch (e) { enumerationReason = e instanceof Error ? e.message : String(e) }
    if (!listed) { const one = (await request(resolved, MAX_BODY, "text/plain, application/octet-stream")).bytes; if (!textual(one)) return JSON.stringify({ ok: false, error: "SKILL.md is binary or not valid UTF-8; rejected", preservation: { status: "incomplete", enumerated: false, reason: "direct URL tree cannot be enumerated", files: [] } }); return JSON.stringify({ ok: false, source_url: resolved, error: "Direct URL tree cannot be enumerated; installation is disabled by default", preservation: { status: "incomplete", enumerated: false, reason: enumerationReason || "direct URL tree cannot be enumerated", files: [{ relativePath: "SKILL.md", url: resolved, checksum: sha(one), bytes: one.length }] }, identity: { upstream_checksum: sha(one) }, pending_dependencies: [], metadata: { status: "incomplete", preservation: { status: "incomplete" } } }) }
    if (listed.length > MAX_FILES) throw new Error("skill contains too many files"); const files: D[] = []; let total = 0; const signals: string[] = []; let binary = false; for (const item of listed) { const b = (await request(item.url, MAX_BODY, "text/plain, application/octet-stream")).bytes; total += b.length; if (total > MAX_TOTAL) throw new Error("skill exceeds total size limit"); const isText = textual(b); if (item.relativePath === "SKILL.md" && !isText) throw new Error("SKILL.md is binary or not valid UTF-8; rejected"); if (!isText) binary = true; else signals.push(...flags(new TextDecoder().decode(b))); files.push({ relativePath: item.relativePath, url: item.url, checksum: sha(b), bytes: b.length, binary_uninspected: !isText }) }
    const securitySignals = [...new Set(signals)]; const approvedBinary = args.allowBinaryUninspected === true && args.approved === true; const complete = files.length === listed.length; const metadata = { status: complete ? "complete" : "incomplete", compatibility: { opencode: "unknown", frameworks: [] }, security: { binary_uninspected: binary, approved: approvedBinary }, dependencies: { pending: [] }, preservation: { status: complete ? "complete" : "incomplete", enumerated: true, files } }; return JSON.stringify({ ok: complete && !securitySignals.length && (!binary || approvedBinary), source_url: resolved, provider, identity: { upstream_checksum: files.find(f => f.relativePath === "SKILL.md")?.checksum || null }, files, binary_uninspected: binary, security_signals: securitySignals, preservation: metadata.preservation, pending_dependencies: pendingDependencies(metadata), requires_binary_approval: binary && !approvedBinary, metadata })
  } catch (e) { return JSON.stringify({ ok: false, error: e instanceof Error ? e.message : String(e), preservation: { status: "incomplete", enumerated: false, reason: "tree enumeration failed", files: [] }, pending_dependencies: [] }) } } })
