/** Bounded, read-only AgentSkillExchange catalog search. */
import { tool } from "@opencode-ai/plugin"
import https from "node:https"
import { lookup } from "node:dns/promises"

const CATALOG = "https://raw.githubusercontent.com/agentskillexchange/skills/main/skills.json"
const MAX_BODY = 2 * 1024 * 1024
const ALLOWED = new Set(["raw.githubusercontent.com", "api.github.com", "github.com", "www.github.com", "agentskillexchange.com", "www.agentskillexchange.com"])
type Dict = Record<string, unknown>
const text = (v: unknown) => typeof v === "string" ? v.trim() : ""
function privateAddress(v: string): boolean { const h = v.toLowerCase().replace(/^\[|\]$/g, ""); if (h === "localhost" || h.endsWith(".localhost") || h.endsWith(".local") || h === "::1" || h === "0.0.0.0" || h === "metadata.google.internal" || h.startsWith("127.") || h.startsWith("169.254.") || /^::ffff:(?:\d{1,3}\.){3}\d{1,3}$/i.test(h) || /^(?:fc|fd|fe[89a-f])/i.test(h)) return true; const p = h.split(".").map(Number); return p.length === 4 && p.every(n => Number.isInteger(n) && n >= 0 && n <= 255) && (p[0] === 10 || p[0] === 127 || (p[0] === 172 && p[1] >= 16 && p[1] <= 31) || (p[0] === 192 && p[1] === 168) || (p[0] === 169 && p[1] === 254)) }
async function fetchPinned(value: string): Promise<Uint8Array> { const url = new URL(value); if (url.protocol !== "https:" || privateAddress(url.hostname) || !ALLOWED.has(url.hostname.toLowerCase())) throw new Error("catalog host is not allowlisted or is private"); const addresses = await lookup(url.hostname, { all: true }); const address = addresses.find(a => !privateAddress(a.address)); if (!address) throw new Error("catalog resolves to a private address"); return await new Promise((resolve, reject) => { const req = https.request(url, { hostname: address.address, port: 443, path: `${url.pathname}${url.search}`, method: "GET", servername: url.hostname, family: address.family, headers: { Accept: "application/json" }, lookup: (_h, _o, cb) => cb(null, address.address, address.family) }, res => { if (res.statusCode !== 200) { res.resume(); reject(new Error(`catalog request failed with HTTP ${res.statusCode}`)); return }; const chunks: Buffer[] = []; let total = 0; res.on("data", c => { total += c.length; if (total > MAX_BODY) req.destroy(new Error(`response exceeds ${MAX_BODY} bytes`)); else chunks.push(c) }); res.on("end", () => resolve(new Uint8Array(Buffer.concat(chunks)))); res.on("error", reject) }); req.setTimeout(10_000, () => req.destroy(new Error("catalog request timed out"))); req.on("error", reject); req.end() }) }
function pendingDependencies(v: Dict) {
  const dependencies = v.dependencies && typeof v.dependencies === "object" ? v.dependencies as Dict : {}
  const pending = Array.isArray(dependencies.pending) ? dependencies.pending : []
  return pending.map(item => typeof item === "string" ? { name: item, status: "pending" } : item)
}
function normalize(v: Dict) { return { slug: text(v.slug) || text(v.id), name: text(v.name) || text(v.title), description: text(v.description) || text(v.summary), category: text(v.category), framework: text(v.framework), verification: text(v.verification), source_url: text(v.source_url) || text(v.sourceUrl), github_repo: text(v.github_repo) || text(v.githubRepo), signals: v.signals ?? [], pending_dependencies: pendingDependencies(v) } }
export default tool({ description: "Searches the remote skill catalog without installing or writing files.", args: { query: tool.schema.string().optional(), category: tool.schema.string().optional(), framework: tool.schema.string().optional(), verification: tool.schema.string().optional(), limit: tool.schema.number().int().min(1).max(100).optional(), catalogUrl: tool.schema.string().optional() }, async execute(args) { const limit = args.limit ?? 20; try { const payload = JSON.parse(new TextDecoder().decode(await fetchPinned(args.catalogUrl?.trim() || CATALOG))); const values = Array.isArray(payload) ? payload : payload && typeof payload === "object" && Array.isArray((payload as Dict).skills) ? (payload as Dict).skills : null; if (!values || values.length > 5000 || !values.every(v => v && typeof v === "object" && !Array.isArray(v))) throw new Error("catalog must contain at most 5000 object entries"); const terms = (args.query || "").toLowerCase().split(/[\s,;]+/).filter(t => t.length > 1); const result = (values as Dict[]).map(normalize).filter(v => { const hay = Object.values(v).filter(x => typeof x === "string").join(" ").toLowerCase(); return terms.every(t => hay.includes(t)) && (!args.category || v.category.toLowerCase() === args.category.trim().toLowerCase()) && (!args.framework || v.framework.toLowerCase() === args.framework.trim().toLowerCase()) && (!args.verification || v.verification.toLowerCase() === args.verification.trim().toLowerCase()) }).slice(0, limit); return { ok: true, provider: "AgentSkillExchange", total: result.length, results: result } } catch (e) { return { ok: false, error: e instanceof Error ? e.message : String(e) } } } })
